# Generated by Django 2.2.2 on 2020-02-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='q_no',
            field=models.IntegerField(default=0),
        ),
    ]
